### ISSUE TITLE
More tests for converters

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#313]
This ticket serves as a reminder for the lack of tests over there. Basically we need to test a lot of conversion options and make sure sos ipynb can be converted back and forth, and there are equal number of cells /sections after conversion.

**Comment by gaow** [comment]
At lease I'll be using this feature myself very frequently from now on as I no longer wish to keep ipynb in my github repo. I can tell immediately if my project notebook has lost information during conversion. Hopefully my daily work covers enough cases to check on this. I'll leave a message to this ticket whenever there is an issue.

**Comment by gaow** [comment]
Ok I'm running into a couple of problems with converter. To reproduce the first one, please open a SoS kerneled ipynb and paste this cell as `markdown`

```
some text ...

|   |  chr |  start |  end |  gene |
|---|---|---|---|---|
|1|     chr11|    1774671 |   1945240 |         CTSD|
|2|     chr11|    1774671 |   1945240 |        TNNT3|

some more text ...
```

and do `sos convert test.ipynb test.sos`, you should get this SoS file:

```
#!/usr/bin/env sos-runner
#fileformat=SOSNB1.0

%cell markdown
#! some text ...
#! |   |  chr |  start |  end |  gene |
#! |---|---|---|---|---|
#! |1|     chr11|    1774671 |   1945240 |         CTSD|
#! |2|     chr11|    1774671 |   1945240 |        TNNT3|
#! some more text ...

%cell code
```
Now run `sos convert test.sos test.ipynb` and open up the notebook file you see the conversion failed. Also potentially the converted SoS file should keep the empty lines between the table and text -- this is how tables work with markdown. You can try this example and see the problem. 

I'll post another problem once we resolve this one :)

**Comment by gaow** [comment]
Well actually on a 2nd look I think the 2nd problem I want to report is the same as the first. Here is my notebook before conversion:

![2016-12-08-17-27-10_scrot](https://cloud.githubusercontent.com/assets/917985/21031933/d66d1de2-bd6b-11e6-9f34-cf58a139c1be.png)

And converted SoS:

```
#!/usr/bin/env sos-runner
#fileformat=SOSNB1.0

%cell markdown
#! # Title

%cell code
[1]
python:
 print('Hi')

%cell code

```

and converting back to ipynb I lost the header title:

![2016-12-08-17-27-46_scrot](https://cloud.githubusercontent.com/assets/917985/21031945/eba21384-bd6b-11e6-859d-d8a01ffd0e65.png)

**Comment by BoPeng** [comment]
Are you sure this is the HEAD? I remember I fixed them today.

**Comment by gaow** [comment]
Yes I'm sure. These problems can be reproduced by current HEAD

**Comment by BoPeng** [comment]
Oh, un-pushed commits on a local machine.

**Comment by BoPeng** [comment]
And make sure to check out the `-e` (`--execute`) option.

**Comment by gaow** [comment]
Nice, it's fixed. 

But the table problem persists. You see in order for a table to properly display the source code has to have spaces before and after, for example here:

###
some text ...

|   |  chr |  start |  end |  gene |
|---|---|---|---|---|
|1|     chr11|    1774671 |   1945240 |         CTSD|
|2|     chr11|    1774671 |   1945240 |        TNNT3|

some more text ...
###

But if you remove the space before / after, which is the case for SoS, then the table will be messed up.

###
some text ...
|   |  chr |  start |  end |  gene |
|---|---|---|---|---|
|1|     chr11|    1774671 |   1945240 |         CTSD|
|2|     chr11|    1774671 |   1945240 |        TNNT3|
some more text ...

###

**Comment by gaow** [comment]
BTW should `--execute` be documented in ` sos convert -l`, or it is left undocumented intentionally for the moment?

**Comment by BoPeng** [comment]
Will check the table issue. I stripped newline at the end of a cell, thinking it should be ok, but perhaps I was wrong.

The --execute is documented online. sos convert -h does not work for it because a plugin system is used so a parser is used only when the from and to formats are determined that triggers the corresponding converter. I can change this behavior but explicitly request converter to register their parsers.

**Comment by gaow** [comment]
Ok ... that explains. But you have some options briefly documented with `sos convert -l` not `-h`. I think it is a great way to do it.

**Comment by BoPeng** [comment]
That only means it is better to let the parser report itself, instead of using a description that is less likely to be updated when the options are changed in the parser.

**Comment by BoPeng** [comment]
Just pushed a patch (https://github.com/BoPeng/SOS/commit/3a68c936ea8db7fc4f1d131ca612cb44cfe05501). A bunch of `parser.print_help` adding together is really ugly, but at lest all information is there now.

**Comment by BoPeng** [comment]
I think the right thing would be

```
sos convert my.sos my.ipynb -h
```
producing the help message for `sos->nb` instead of `sos convert`, and

```
sos convert -h
```

would list all converters...

**Comment by BoPeng** [comment]
I hate the `-l` option so much so I got rid of it with complex argparse hack. The new interface is documented at http://bopeng.github.io/SOS/doc/tutorials/File_Conversion.html .

https://github.com/BoPeng/SOS/commit/2011309efe8bb408f84d35e2d5a6cedaf0bc683a
